---
# ansible -m copy -a "src=master.gitconfig dest=~/.gitconfig" localhost

# to run: ansible-playbook playbook.yml -v

- name: Ensure ~/.gitconfig" copied from master.gitconfig
  gather_facts: false
  hosts: localhost
  tasks: 
    - copy: src="../adhoc/master.gitconfig" dest="~/.gitconfig"

- name: Ensure homebrew packages are installed.
  hosts: localhost
  tasks:
    - homebrew: name=bat state=latest
    - homebrew: 
      name: jq
        state: latest